import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-xl text-blue-500'>
        saman
      </h1>
    </div>
  )
}
