import Head from 'next/head'


export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Phone Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1 className='text-xl'>
       saman
     </h1>
    </div>
  )
}
